//! Web Server — Serve HTTP requests from TrustZone.
//!
//! Runs a simple HTTP server that handles requests from the host machine.
//! The Trusted OS listens on 10.0.0.1:8080 and forwards requests to this
//! applet via RPC.
//!
//! From the host:
//!   curl http://10.0.0.1:8080/
//!   curl http://10.0.0.1:8080/hello
//!   curl http://10.0.0.1:8080/random
//!   curl -X POST -d "some data" http://10.0.0.1:8080/echo
//!
//! To build: cp examples/webserver/main.rs src/main.rs && make

#![no_std]
#![no_main]

use core::fmt::Write;
use gotee_syscall::{self, http, log};

#[no_mangle]
pub extern "C" fn _start() -> ! {
    log!("Web Server example");
    log!("Serving HTTP on 10.0.0.1:8080");
    log!("Try: curl http://10.0.0.1:8080/hello");

    http::serve(|req, resp| {
        log!("{} {}", req.method, req.path);

        match (req.method, req.path) {
            // Home page
            (_, "/") => {
                resp.set_content_type("text/html");
                resp.set_body(
                    b"<h1>Hello from TrustZone!</h1>\
                      <p>This response was generated by a Rust applet running in ARM TrustZone Secure World.</p>\
                      <ul>\
                        <li><a href=\"/hello\">/hello</a> - Plain text greeting</li>\
                        <li><a href=\"/random\">/random</a> - Hardware random number</li>\
                        <li><a href=\"/time\">/time</a> - System nanotime</li>\
                      </ul>\
                      <p>Try: <code>curl -X POST -d 'your data' http://10.0.0.1:8080/echo</code></p>",
                );
            }

            // Plain text greeting
            (_, "/hello") => {
                resp.set_content_type("text/plain");
                resp.set_body(b"Hello from TrustZone Secure World!");
            }

            // Hardware random number
            (_, "/random") => {
                let mut rng = [0u8; 32];
                gotee_syscall::getrandom(&mut rng);

                // Format as hex string
                let mut hex = [0u8; 256];
                let mut w = BufWriter::new(&mut hex);
                write!(w, "{{\"random\":\"").ok();
                for b in &rng {
                    write!(w, "{:02x}", b).ok();
                }
                write!(w, "\"}}").ok();
                let len = w.pos;

                resp.set_content_type("application/json");
                resp.set_body(&hex[..len]);
            }

            // System time
            (_, "/time") => {
                let ns = gotee_syscall::nanotime();
                let mut buf = [0u8; 128];
                let mut w = BufWriter::new(&mut buf);
                write!(w, "{{\"nanotime\":{}}}", ns).ok();
                let len = w.pos;

                resp.set_content_type("application/json");
                resp.set_body(&buf[..len]);
            }

            // Echo back POST body
            ("POST", "/echo") => {
                resp.set_content_type(if req.content_type.is_empty() {
                    "text/plain"
                } else {
                    req.content_type
                });
                resp.set_body(req.body.as_bytes());
            }

            // 404 for everything else
            _ => {
                resp.status = 404;
                resp.set_content_type("text/plain");
                resp.set_body(b"404 Not Found");
            }
        }
    });
}

/// Minimal buffer writer for formatting without an allocator.
struct BufWriter<'a> {
    buf: &'a mut [u8],
    pos: usize,
}

impl<'a> BufWriter<'a> {
    fn new(buf: &'a mut [u8]) -> Self {
        Self { buf, pos: 0 }
    }
}

impl<'a> Write for BufWriter<'a> {
    fn write_str(&mut self, s: &str) -> core::fmt::Result {
        let bytes = s.as_bytes();
        let remaining = self.buf.len() - self.pos;
        let len = bytes.len().min(remaining);
        self.buf[self.pos..self.pos + len].copy_from_slice(&bytes[..len]);
        self.pos += len;
        if len < bytes.len() {
            Err(core::fmt::Error)
        } else {
            Ok(())
        }
    }
}
